set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports I_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports O_rx_done]
set_property IOSTANDARD LVCMOS33 [get_ports O_spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports O_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports O_spi_sck]
set_property IOSTANDARD LVCMOS33 [get_ports O_tx_done]
set_property PACKAGE_PIN R14 [get_ports I_rst_n]
set_property PACKAGE_PIN A14 [get_ports O_rx_done]
set_property PACKAGE_PIN G15 [get_ports O_spi_cs]
set_property PACKAGE_PIN H13 [get_ports O_spi_mosi]
set_property PACKAGE_PIN J15 [get_ports O_spi_sck]
set_property PACKAGE_PIN A19 [get_ports O_tx_done]
set_property PACKAGE_PIN AA3 [get_ports {state[4]}]
set_property PACKAGE_PIN AA4 [get_ports {state[3]}]
set_property PACKAGE_PIN AA5 [get_ports {state[2]}]
set_property PACKAGE_PIN AA6 [get_ports {state[1]}]
set_property PACKAGE_PIN AA8 [get_ports {state[0]}]

set_property PACKAGE_PIN AB1 [get_ports {O_data_out[7]}]
set_property PACKAGE_PIN AB2 [get_ports {O_data_out[6]}]
set_property PACKAGE_PIN AB3 [get_ports {O_data_out[5]}]
set_property PACKAGE_PIN AB5 [get_ports {O_data_out[4]}]
set_property PACKAGE_PIN AB6 [get_ports {O_data_out[3]}]
set_property PACKAGE_PIN AB7 [get_ports {O_data_out[2]}]
set_property PACKAGE_PIN AB8 [get_ports {O_data_out[1]}]
set_property PACKAGE_PIN AB10 [get_ports {O_data_out[0]}]


set_property PACKAGE_PIN G17 [get_ports I_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports I_spi_miso]

set_property PACKAGE_PIN V4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
